/* ============================================================================
   SEO
   ============================================================================
   Everything a crawler reads lives here: the identity Google resolves the
   business against, the per-page titles and descriptions, and the structured
   data graph.

   Two rules this file follows, because breaking either one costs rankings
   rather than gaining them:

     1. Nothing is invented. Every claim in the structured data — the phone
        number, the disciplines, the cities, the people — is already stated on
        the site or was supplied by the client. Schema that contradicts the
        visible page is a manual-action risk, not a ranking trick.

     2. Identity is stated once. The Organization node carries a stable @id and
        every other node points at it, so Google merges the home page, the
        contact page, the logo and the social profiles into one entity instead
        of guessing at four.

   ── WHAT IS STILL OWED ─────────────────────────────────────────────────────
   Marked `TODO` below. These are the highest-value gaps left, in order:

     a. A street address + opening hours. Without them the business cannot rank
        in the Google Maps pack, which is where most "near me" searches for a
        photographer actually convert. Fill in `postalAddress` and `hours`.
     b. A verified Google Business Profile, linked from `sameAs`.
     c. Real case studies in the Work section. Six indexable project pages with
        their own photographs beat any amount of meta-tag work.
   ========================================================================= */

import {
  contact,
  socials,
  services,
  team,
  markets,
  workCategories,
  faq,
  clientReviews,
  type Market,
  type WorkCategory,
} from "../content/site";
import {
  esWork,
  esHome,
  esContact,
  esFaq,
  type EsCategory,
} from "../content/site.es";

/* -------------------------------------------------------------- constants */

/**
 * The canonical origin, with the `www` the host actually serves — the apex
 * 308-redirects to it. Must stay identical to `site` in astro.config.mjs and to
 * the Sitemap: line in public/robots.txt; `npm run check:seo` fails if it does not.
 */
export const SITE_URL = "https://www.jpmediagroups.com";
export const SITE_NAME = "JP Media Groups";

/** The site is written in one language. Stated explicitly so hreflang is honest. */
export const LOCALE = "en_US";
export const LANG = "en";

/**
 * The Spanish half of the site.
 *
 * Was `es_CO` when Colombia was a market. It is `es_US` now: the audience is
 * Utah's Spanish-speaking residents, not Colombia, and a locale naming a
 * country the studio does not serve is the same claim the rest of this change
 * removed — stated in a tag instead of in prose.
 */
export const LOCALE_ALT = ["es_US"];

/** Stable node ids. Never change these: they are how Google keeps the entity together. */
export const ID = {
  org: `${SITE_URL}/#organization`,
  website: `${SITE_URL}/#website`,
  logo: `${SITE_URL}/#logo`,
};

/**
 * Where the photographs' terms of use live — /licensing/.
 *
 * Search Console flagged every gallery image as missing `license` and
 * `acquireLicensePage`. Both fields have to be crawlable page URLs: Google
 * rejects a `mailto:`, a fragment, or anything it cannot fetch, so the page
 * exists rather than the fields pointing at /contact/ and hoping.
 *
 * Emitting them is also what makes the images eligible for the "Licensable"
 * badge in Google Images, which is a real channel for a photography studio.
 * Keep the page indexable — a `noindex` here silently disqualifies every image.
 */
export const LICENSE_PAGE = `${SITE_URL}/licensing/`;

/**
 * The default share card. 1200×630, generated by `npm run og`.
 * Absolute URLs are required — every scraper except Google refuses relative ones.
 */
export const OG = {
  image: "/og/jp-media-groups.jpg",
  width: 1200,
  height: 630,
  alt: "JP Media Groups — video production, photography and marketing in Utah.",
};

/**
 * Utah is the primary local market, so the geo meta names it. These are
 * legacy tags — Google ignores them — but Bing and several local-directory
 * crawlers still read them, and they cost nothing.
 */
export const GEO = {
  region: "US-UT",
  placename: "Utah",
};

/* --------------------------------------------------------------- keywords */
/* The `keywords` meta tag is dead for ranking. This list is not for that tag —
   it is the vocabulary the titles, descriptions and schema below are written
   against, kept in one place so the phrasing stays consistent across pages and
   so there is something concrete to check Search Console impressions against. */

export const KEYWORDS = {
  core: [
    "marketing agency",
    "creative agency",
    "video production",
    "photography",
    "audiovisual production",
  ],
  services: [
    "music video production",
    "commercial video production",
    "advertising campaign production",
    "food photography",
    "restaurant photography",
    "corporate photography",
    "brand photography",
    "social media content creation",
    "branding agency",
  ],
  /* One service area, so one state and one city. This list used to carry nine
     entries across two countries; the other seven were the vocabulary the
     deleted market pages were written against. Adding a place back here is
     adding it to the site's whole keyword surface — see the service-area note
     at the top of content/site.ts before doing it. */
  places: ["Utah", "Salt Lake City"],
};

/**
 * Every combination the market pages are written to answer. Generated rather
 * than typed out so a new market cannot ship with half its terms missing.
 */
export const marketKeywords = markets.flatMap((m) =>
  [
    "marketing agency",
    "video production",
    "photography",
    "creative agency",
  ].flatMap((term) => [
    `${term} ${m.name}`,
    ...m.cities.map((c) => `${term} ${c}`),
  ]),
);

/**
 * The portfolio's own vocabulary, crossed with the markets.
 *
 * "wedding photographer utah" is a different search from "marketing agency
 * utah" and converts far better, because somebody typing it has already
 * decided what they want. Each category page is written to answer one of these.
 */
export const workKeywords = workCategories.flatMap((c) => [
  c.name.toLowerCase(),
  ...markets.map((m) => `${c.name.toLowerCase()} ${m.name}`),
]);

/* ----------------------------------------------------------- page records */

export interface PageSeo {
  /** Under ~60 characters so it is not truncated in the result. */
  title: string;
  /** 140–160 characters, written to earn the click, not to stuff terms. */
  description: string;
  /** Path-relative share card. Falls back to the default. */
  image?: string;
  imageAlt?: string;
  type?: "website" | "article" | "profile";
  /** Keeps a page out of the index without keeping crawlers off it. */
  noindex?: boolean;
  /** Trail shown in the result, home excluded — it is added automatically. */
  breadcrumbs?: Array<{ name: string; path: string }>;
  /** Extra schema nodes merged into the page graph. */
  schema?: Record<string, unknown>[];
}

export const abs = (path: string) => new URL(path, SITE_URL).href;

/* ------------------------------------------------------------ the entity */

/**
 * TODO — supply and this becomes eligible for the Maps pack.
 * Set `postalAddress` to the real studio address and `hours` to the real
 * opening hours, then flip `LOCAL` to true. Leaving it false is deliberate:
 * a LocalBusiness node with no address is worse than none at all.
 */
const LOCAL = false;
const postalAddress = {
  streetAddress: "300 South Spring Street", // TODO
  addressLocality: "200 N Spring St", // TODO — e.g. 'Salt Lake City'
  addressRegion: "CA",
  postalCode: "90012", // TODO
  addressCountry: "US",
};
const hours = ["Mo-Fr 09:00-18:00"]; // TODO — confirm

/**
 * The business, as one node.
 *
 * `ProfessionalService` is used rather than bare `Organization` because it is
 * a LocalBusiness subtype: it accepts areaServed, priceRange and hours, which
 * is what makes the node eligible for local treatment once the address lands.
 */
export function organization(): Record<string, unknown> {
  const node: Record<string, unknown> = {
    "@type": ["Organization", "ProfessionalService"],
    "@id": ID.org,
    name: SITE_NAME,

    // Brand search is the highest-converting traffic a studio gets, and people
    // do not type the registered name. They type "JP media", "JP media group"
    // singular, or run the words together. Every spelling the business is
    // actually searched by is declared so Google resolves them all to one
    // entity instead of treating them as unrelated strings.
    alternateName: [
      "JP Media",
      "JP Media Group",
      "JPMedia",
      "JP Media Groups Utah",
      "JPMG",
      "JP",
      "jp",
    ],

    url: SITE_URL,
    logo: { "@id": ID.logo },
    image: { "@id": ID.logo },
    description:
      "Creative agency specialising in audiovisual production, professional photography, music videos, branding and strategic marketing.",
    slogan: "Every brand has a story worth telling",
    foundingDate: "2016",
    email: contact.email,
    telephone: contact.phone,

    // Where the work actually happens. Built from the same market records the
    // market page renders, so the schema and the visible pages can never drift
    // apart — which is exactly the property that matters while a Business
    // Profile appeal is open, because Google reads this node and the page in
    // the same crawl and a contradiction between them is the thing that sinks
    // an appeal.
    //
    // This list used to end with `{ "@type": "Country", name: "United States" }`
    // as a catch-all above the five markets. That node is gone: it declared a
    // nationwide service area in structured data, which is a broader claim than
    // anything the site says in prose and broader than the business can
    // document. State and city only.
    areaServed: [
      ...markets.map((m) => ({
        "@type": m.kind,
        name: m.name,
        ...(m.region
          ? { address: { "@type": "PostalAddress", addressRegion: m.region } }
          : {}),
      })),
      ...markets.flatMap((m) =>
        m.cities.map((c) => ({ "@type": "City", name: c })),
      ),
    ],

    knowsAbout: [
      ...KEYWORDS.core,
      ...KEYWORDS.services,
      ...KEYWORDS.places,
      ...marketKeywords,
      ...workKeywords,
    ],
    knowsLanguage: ["en", "es"],

    // The five disciplines, as an offer catalogue. This is what lets Google
    // answer "what do they do" without parsing the prose.
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "Services",
      itemListElement: services.items.map((s, i) => ({
        "@type": "Offer",
        position: i + 1,
        itemOffered: {
          "@type": "Service",
          name: s.title,
          description: s.body,
          serviceType: s.title,
          provider: { "@id": ID.org },
        },
      })),
    },

    // Referenced by @id rather than inlined. The Person nodes are emitted once
    // as their own entries in the graph (see `people()`), so the team exists as
    // four resolvable entities Google can attach to the organisation instead of
    // four anonymous objects buried inside it. That is what lets a search for
    // a person's name resolve to this business.
    employee: team.members.map((m) => ({ "@id": personId(m.name) })),

    // Every profile the business controls. This is the single strongest signal
    // for entity resolution — add the Google Business Profile, YouTube, Vimeo,
    // LinkedIn, Behance and TikTok URLs here as they exist.
    sameAs: socials.map((s) => s.href),

    contactPoint: {
      "@type": "ContactPoint",
      contactType: "sales",
      email: contact.email,
      telephone: contact.phone,
      areaServed: ["US", "CO"],
      availableLanguage: ["English", "Spanish"],
    },
  };

  if (LOCAL) {
    node.address = { "@type": "PostalAddress", ...postalAddress };
    node.openingHours = hours;
    node.priceRange = "$$";
  }

  // Attached only when there are real reviews behind it. An `aggregateRating`
  // on a business with no reviews is the schema equivalent of printing a star
  // rating on the letterhead.
  if (clientReviews.length) node.aggregateRating = { "@id": `${SITE_URL}/#rating` };

  return node;
}

/**
 * A stable @id per person, derived from the name.
 *
 * Anchored on the home page because that is where the team section is rendered.
 * Never change the shape: an @id is how Google keeps an entity together across
 * crawls, and rewriting one reads as a different person appearing.
 */
export const personId = (name: string) =>
  `${SITE_URL}/#person-${name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")}`;

/**
 * The team, as real entities.
 *
 * These were inlined inside `employee` as bare objects, which tells Google that
 * four people exist and nothing else — there is no @id to point at, so nothing
 * else in the graph, on this site or anywhere on the web, can refer to them.
 * As nodes they are addressable, which is the whole mechanism behind a name
 * search resolving to the business that employs them.
 *
 * Only what the site already states about each person: name, role, work email.
 * No years, no schools, no awards — those are claims about real people and none
 * were supplied.
 */
export function people(): Record<string, unknown>[] {
  return team.members.map((m) => ({
    "@type": "Person",
    "@id": personId(m.name),
    name: m.name,
    jobTitle: m.role,
    email: m.email,
    worksFor: { "@id": ID.org },
    url: `${SITE_URL}/#team`,
  }));
}

/**
 * Reviews, and the rating they average to.
 *
 * Returns nothing at all while `clientReviews` is empty, which is the point:
 * an AggregateRating with no reviews behind it is fabricated structured data,
 * not a placeholder. See the warning above the array in content/site.ts.
 *
 * `bestRating` is stated explicitly. Left out, a 4.8 is ambiguous between a
 * five-point and a ten-point scale, and Google has to guess which.
 */
export function reviewNodes(): Record<string, unknown>[] {
  if (!clientReviews.length) return [];

  const total = clientReviews.reduce((n, r) => n + r.rating, 0);
  const average = Math.round((total / clientReviews.length) * 10) / 10;

  return [
    {
      "@type": "AggregateRating",
      "@id": `${SITE_URL}/#rating`,
      itemReviewed: { "@id": ID.org },
      ratingValue: average,
      reviewCount: clientReviews.length,
      bestRating: 5,
      worstRating: 1,
    },
    ...clientReviews.map((r, i) => ({
      "@type": "Review",
      "@id": `${SITE_URL}/#review-${i + 1}`,
      itemReviewed: { "@id": ID.org },
      author: { "@type": "Person", name: r.author },
      datePublished: r.date,
      reviewBody: r.body,
      reviewRating: {
        "@type": "Rating",
        ratingValue: r.rating,
        bestRating: 5,
        worstRating: 1,
      },
      ...(r.verifiedOn ? { url: r.verifiedOn } : {}),
    })),
  ];
}

/**
 * The FAQ, as a node.
 *
 * ⚠️  This does NOT produce a rich result. Google deprecated the FAQ rich
 *     result in May 2026 and it appears for nobody. The node is emitted for
 *     what survived: FAQPage is still valid Schema.org and is still read by the
 *     retrieval systems behind AI answers.
 *
 *     The one hard rule is that every question and answer here must be VISIBLE
 *     on the page that emits this. Markup describing content a visitor cannot
 *     see is a structured-data violation, and it always has been - the rich
 *     result going away does not soften it, it only removes the reward.
 */
export function faqNode(url: string): Record<string, unknown> {
  return {
    "@type": "FAQPage",
    "@id": `${url}#faq`,
    mainEntity: faq.items.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };
}

/** The logo, as its own node so both the Organization and the site can cite it. */
export function logoNode(): Record<string, unknown> {
  return {
    "@type": "ImageObject",
    "@id": ID.logo,
    url: abs("/icons/icon-512.png"),
    contentUrl: abs("/icons/icon-512.png"),
    width: 512,
    height: 512,
    caption: SITE_NAME,
  };
}

export function website(): Record<string, unknown> {
  return {
    "@type": "WebSite",
    "@id": ID.website,
    url: SITE_URL,
    name: SITE_NAME,
    description:
      "Video production, professional photography and strategic marketing for brands, restaurants and artists.",
    publisher: { "@id": ID.org },
    inLanguage: LANG,
  };
}

/**
 * The breadcrumb trail. Home is prepended here so no page has to repeat it,
 * and the current page is included as the last item — Google drops trails that
 * do not terminate on the page they are served from.
 */
export function breadcrumbs(
  trail: Array<{ name: string; path: string }>,
  url: string,
): Record<string, unknown> | null {
  if (!trail.length) return null;
  const items = [{ name: "Home", path: "/" }, ...trail];
  return {
    "@type": "BreadcrumbList",
    "@id": `${url}#breadcrumb`,
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: abs(item.path),
    })),
  };
}

export function webPage(page: PageSeo, url: string): Record<string, unknown> {
  const node: Record<string, unknown> = {
    "@type": "WebPage",
    "@id": `${url}#webpage`,
    url,
    name: page.title,
    description: page.description,
    isPartOf: { "@id": ID.website },
    about: { "@id": ID.org },
    primaryImageOfPage: { "@id": ID.logo },
    inLanguage: LANG,
  };
  if (page.breadcrumbs?.length)
    node.breadcrumb = { "@id": `${url}#breadcrumb` };
  return node;
}

/**
 * Assembles the page's whole graph as ONE script tag.
 *
 * A single `@graph` is deliberate. Multiple separate JSON-LD blocks are legal,
 * but nodes in different blocks cannot reference each other by @id, so the
 * Organization, the page and the breadcrumb end up as three unrelated islands.
 */
export function jsonLd(page: PageSeo, url: string): string {
  const graph = [
    organization(),
    logoNode(),
    // The Person nodes travel with the Organization rather than living only on
    // the home page, because `organization().employee` points at them by @id on
    // every page — a reference that resolves to nothing is a dangling edge, and
    // `npm run check:seo` fails the page for it.
    ...people(),
    // Empty until there are real reviews. See content/site.ts.
    ...reviewNodes(),
    website(),
    webPage(page, url),
    breadcrumbs(page.breadcrumbs ?? [], url),
    ...(page.schema ?? []),
  ].filter(Boolean);

  return JSON.stringify({ "@context": "https://schema.org", "@graph": graph });
}

/* ------------------------------------------------------------ page copy */
/* Titles are front-loaded: the terms people search sit before the brand name,
   because Google truncates the tail and users scan the head. */

export const pages = {
  home: {
    // One market now, so the title can spend its 60 characters on what the
    // studio does instead of splitting them across states.
    // "JP Media" rather than the full name is deliberate — it is a real
    // alternateName, it catches the brand searches people actually type, and
    // Google prints "JP Media Groups" above the title from the schema anyway.
    title: "Photography, Video & Marketing in Utah | JP Media",
    description:
      "Creative agency in Utah for video production, photography and marketing. Music videos, commercials, food photography and branding, produced in Salt Lake City.",
    image: "/og/jp-media-groups.jpg",
    // A home page is the site root; a breadcrumb trail on it is noise.
    breadcrumbs: [],
  },

  contact: {
    title: "Contact — Start a Project | JP Media Groups",
    description:
      "Tell JP Media Groups about your project. Video production, photography, music videos, branding and marketing in Utah, in English and in Spanish.",
    image: "/og/contact.jpg",
    imageAlt:
      "Contact JP Media Groups — start a video, photography or marketing project.",
    breadcrumbs: [{ name: "Contact", path: "/contact/" }],
    schema: [
      {
        "@type": "ContactPage",
        "@id": `${SITE_URL}/contact/#contactpage`,
        url: `${SITE_URL}/contact/`,
        name: "Contact JP Media Groups",
        mainEntity: { "@id": ID.org },
      },
      // The questions are rendered on this page, right under the form. That is
      // not a formality: markup for answers a visitor cannot see is a
      // violation, and the answers are the reason the block exists at all.
      faqNode(`${SITE_URL}/contact/`),
    ],
  },

  /**
   * One record per market, built from the same data the page renders. There is
   * one market: Utah.
   *
   * With a single service area this page and the home page are the two URLs on
   * the site competing for the same searcher, so they are written to be about
   * different things — the home page is about the studio, /utah/ is about the
   * work in the state. Near-identical pages are doorway pages and Google
   * demotes them, and two pages saying the same thing about one place is the
   * shape it looks for. Keep the copy in `markets[0].body` distinct from
   * `about.body`.
   */
  market(m: Market): PageSeo {
    return {
      // The market leads the title. Brand goes last: Google truncates the tail
      // and the searcher scans the head.
      title: `Marketing, Video & Photography in ${m.name} | JP Media`,
      description: m.metaDescription,
      breadcrumbs: [{ name: m.name, path: `/${m.slug}/` }],
      schema: [
        {
          "@type": "Service",
          "@id": `${SITE_URL}/${m.slug}/#service`,
          name: `Marketing, video production and photography in ${m.name}`,
          description: m.lead,
          serviceType: m.leads,
          provider: { "@id": ID.org },
          areaServed: [
            {
              "@type": m.kind,
              name: m.name,
              ...(m.region
                ? {
                    address: {
                      "@type": "PostalAddress",
                      addressRegion: m.region,
                    },
                  }
                : {}),
            },
            ...m.cities.map((c) => ({ "@type": "City", name: c })),
          ],
          hasOfferCatalog: {
            "@type": "OfferCatalog",
            name: `Services in ${m.name}`,
            itemListElement: m.leads.map((title, i) => {
              const s = services.items.find((x) => x.title === title);
              return {
                "@type": "Offer",
                position: i + 1,
                itemOffered: {
                  "@type": "Service",
                  name: `${title} — ${m.name}`,
                  description: s?.body ?? "",
                  provider: { "@id": ID.org },
                },
              };
            }),
          },
        },
      ],
    };
  },

  /**
   * The portfolio index. The one page that says "here is the work" and links
   * every category, which is what makes the six of them crawlable from one
   * place instead of only from the nav.
   */
  work: {
    title: "Work — Photography, Video & Websites | JP Media Groups",
    description:
      "Selected work by JP Media Groups: wedding and food photography, music videos, corporate and brand images, social media content and websites.",
    breadcrumbs: [{ name: "Work", path: "/work/" }],
  },

  /**
   * One record per portfolio category.
   *
   * These pages carry photographs, which is the reason they exist twice over:
   * a photography studio that ranks for "wedding photographer" ranks on its
   * pictures, and Google Images is a channel the market pages cannot reach.
   * That is why `ImageGallery` is emitted with a real image count rather than
   * a generic CollectionPage — and why the count is read from the folder, so
   * schema and page can never disagree.
   */
  workCategory(
    c: WorkCategory,
    images: { url: string; caption: string }[],
    es?: EsCategory,
  ): PageSeo {
    // One function for both languages, so a Spanish category page cannot ship
    // with an English title, an English description, or — worse — a @id and a
    // breadcrumb pointing at the English URL, which would make the two pages
    // fight each other instead of pairing through hreflang.
    const path = es ? `/es/trabajo/${es.slug}/` : `/work/${c.slug}/`;
    const name = es ? es.name : c.name;
    const short = es ? es.short : c.short;
    const lead = es ? es.lead : c.lead;

    const node: Record<string, unknown> = {
      "@type": c.kind === "web" ? "CollectionPage" : "ImageGallery",
      "@id": `${SITE_URL}${path}#gallery`,
      name: `${name} — JP Media Groups`,
      description: lead,
      inLanguage: es ? "es" : LANG,
      isPartOf: { "@id": ID.website },
      about: { "@id": ID.org },
    };

    // Only claim images when there are images. An empty gallery node is a
    // structured-data error, not a placeholder.
    //
    // `license` and `acquireLicensePage` complete the set Google's image
    // metadata feature asks for. They were the two fields Search Console
    // reported missing on /work/food/, and without them the credit and
    // copyright below are read but the images are never marked licensable.
    if (images.length) {
      node.numberOfItems = images.length;
      node.associatedMedia = images.map((img) => ({
        "@type": "ImageObject",
        contentUrl: img.url,
        caption: img.caption,
        creditText: SITE_NAME,
        creator: { "@id": ID.org },
        copyrightNotice: `© ${SITE_NAME}`,
        license: LICENSE_PAGE,
        acquireLicensePage: LICENSE_PAGE,
      }));
    }

    return {
      title: es ? es.title : `${c.name} | JP Media Groups`,
      description: es ? es.metaDescription : c.metaDescription,
      breadcrumbs: es
        ? [
            { name: "Trabajo", path: "/es/trabajo/" },
            { name: short, path },
          ]
        : [
            { name: "Work", path: "/work/" },
            { name: short, path },
          ],
      schema: [
        node,
        {
          "@type": "Service",
          "@id": `${SITE_URL}${path}#service`,
          name,
          description: lead,
          serviceType: c.discipline,
          provider: { "@id": ID.org },
          areaServed: markets.map((m) => ({ "@type": m.kind, name: m.name })),
          ...(es ? { availableLanguage: ["es", "en"] } : {}),
        },
      ],
    };
  },

  /**
   * The page `license` and `acquireLicensePage` point at.
   *
   * It must stay indexable and reachable: Google fetches it to validate the
   * image metadata, and a `noindex` or a broken link here takes every gallery
   * image out of the licensable set along with it. It is linked from the
   * footer for the same reason — an orphan page is crawled late or not at all.
   */
  licensing: {
    title: "Image Licensing & Usage | JP Media Groups",
    description:
      "Usage terms for the photography on jpmediagroups.com. Every image is © JP Media Groups; licensing for press, publishers and brands is quoted per use.",
    breadcrumbs: [{ name: "Image licensing", path: "/licensing/" }],
    schema: [
      {
        "@type": "WebPage",
        "@id": `${LICENSE_PAGE}#licensing`,
        url: LICENSE_PAGE,
        name: "Image licensing — JP Media Groups",
        description:
          "Copyright and licensing terms for the photography published on jpmediagroups.com.",
        publisher: { "@id": ID.org },
        about: { "@id": ID.org },
      },
    ],
  },

  /* ------------------------------------------------------------- español */
  /* Escritos, no traducidos. Un título en español calcado del inglés compite
     con su propia contraparte en vez de responder una búsqueda distinta. */

  homeEs: {
    title: esHome.title,
    description: esHome.metaDescription,
    image: "/og/jp-media-groups.jpg",
    breadcrumbs: [],
  },

  workEs: {
    title: esWork.title,
    description: esWork.metaDescription,
    breadcrumbs: [{ name: esWork.crumb, path: "/es/trabajo/" }],
  },

  contactEs: {
    title: esContact.title,
    description: esContact.metaDescription,
    image: "/og/contact.jpg",
    imageAlt:
      "Contacto JP Media Groups — empezá un proyecto de video, fotografía o marketing.",
    breadcrumbs: [{ name: esContact.crumb, path: "/es/contacto/" }],
    schema: [
      {
        "@type": "ContactPage",
        "@id": `${SITE_URL}/es/contacto/#contactpage`,
        url: `${SITE_URL}/es/contacto/`,
        name: "Contacto — JP Media Groups",
        inLanguage: "es",
        mainEntity: { "@id": ID.org },
      },
      {
        "@type": "FAQPage",
        "@id": `${SITE_URL}/es/contacto/#faq`,
        inLanguage: "es",
        mainEntity: esFaq.items.map((item) => ({
          "@type": "Question",
          name: item.q,
          acceptedAnswer: { "@type": "Answer", text: item.a },
        })),
      },
    ],
  },

  notFound: {
    title: "Page Not Found | JP Media Groups",
    description:
      "That page does not exist. Head back to JP Media Groups — video production, photography and marketing in Utah.",
    // A 404 that gets indexed competes with the pages that matter.
    noindex: true,
    breadcrumbs: [],
  },
} satisfies Record<
  string,
  | PageSeo
  | ((m: Market) => PageSeo)
  | ((c: WorkCategory, images: { url: string; caption: string }[]) => PageSeo)
>;
