/* ============================================================================
   SEO
   ============================================================================
   Everything a crawler reads lives here: the identity Google resolves the
   business against, the per-page titles and descriptions, and the structured
   data graph.

   Two rules this file follows, because breaking either one costs rankings
   rather than gaining them:

     1. Nothing is invented. Every claim in the structured data — the phone
        number, the disciplines, the cities, the people — is already stated on
        the site or was supplied by the client. Schema that contradicts the
        visible page is a manual-action risk, not a ranking trick.

     2. Identity is stated once. The Organization node carries a stable @id and
        every other node points at it, so Google merges the home page, the
        contact page, the logo and the social profiles into one entity instead
        of guessing at four.

   ── WHAT IS STILL OWED ─────────────────────────────────────────────────────
   Marked `TODO` below. These are the highest-value gaps left, in order:

     a. A street address + opening hours. Without them the business cannot rank
        in the Google Maps pack, which is where most "near me" searches for a
        photographer actually convert. Fill in `postalAddress` and `hours`.
     b. A verified Google Business Profile, linked from `sameAs`.
     c. Real case studies in the Work section. Six indexable project pages with
        their own photographs beat any amount of meta-tag work.
   ========================================================================= */

import { contact, socials, services, team, markets, type Market } from '../content/site';

/* -------------------------------------------------------------- constants */

/**
 * The canonical origin, with the `www` the host actually serves — the apex
 * 308-redirects to it. Must stay identical to `site` in astro.config.mjs and to
 * the Sitemap: line in public/robots.txt; `npm run check:seo` fails if it does not.
 */
export const SITE_URL = 'https://www.jpmediagroups.com';
export const SITE_NAME = 'JP Media Groups';

/** The site is written in one language. Stated explicitly so hreflang is honest. */
export const LOCALE = 'en_US';
export const LANG = 'en';

/** Secondary audience — Colombia. Signals the market, does not promise a page. */
export const LOCALE_ALT = ['es_CO'];

/** Stable node ids. Never change these: they are how Google keeps the entity together. */
export const ID = {
  org: `${SITE_URL}/#organization`,
  website: `${SITE_URL}/#website`,
  logo: `${SITE_URL}/#logo`,
};

/**
 * The default share card. 1200×630, generated by `npm run og`.
 * Absolute URLs are required — every scraper except Google refuses relative ones.
 */
export const OG = {
  image: '/og/jp-media-groups.jpg',
  width: 1200,
  height: 630,
  alt: 'JP Media Groups — video production, photography and marketing across Utah, Miami, New York, Los Angeles and Colombia.',
};

/**
 * Utah is the primary local market, so the geo meta names it. These are
 * legacy tags — Google ignores them — but Bing and several local-directory
 * crawlers still read them, and they cost nothing.
 */
export const GEO = {
  region: 'US-UT',
  placename: 'Utah',
};

/* --------------------------------------------------------------- keywords */
/* The `keywords` meta tag is dead for ranking. This list is not for that tag —
   it is the vocabulary the titles, descriptions and schema below are written
   against, kept in one place so the phrasing stays consistent across pages and
   so there is something concrete to check Search Console impressions against. */

export const KEYWORDS = {
  core: [
    'marketing agency',
    'creative agency',
    'video production',
    'photography',
    'audiovisual production',
  ],
  services: [
    'music video production',
    'commercial video production',
    'advertising campaign production',
    'food photography',
    'restaurant photography',
    'corporate photography',
    'brand photography',
    'social media content creation',
    'branding agency',
  ],
  /* The state names matter as much as the city names, and for a search like
     "marketing california" they matter more. Somebody looking for an agency
     types the state roughly as often as the city, and a site that only ever
     says "Los Angeles" cannot answer them. Each of these has a page. */
  places: [
    'Utah',
    'Salt Lake City',
    'California',
    'Los Angeles',
    'Florida',
    'Miami',
    'New York',
    'Colombia',
    'Bogotá',
  ],
};

/**
 * Every combination the market pages are written to answer. Generated rather
 * than typed out so a new market cannot ship with half its terms missing.
 */
export const marketKeywords = markets.flatMap((m) =>
  ['marketing agency', 'video production', 'photography', 'creative agency'].flatMap((term) => [
    `${term} ${m.name}`,
    ...m.cities.map((c) => `${term} ${c}`),
  ]),
);

/* ----------------------------------------------------------- page records */

export interface PageSeo {
  /** Under ~60 characters so it is not truncated in the result. */
  title: string;
  /** 140–160 characters, written to earn the click, not to stuff terms. */
  description: string;
  /** Path-relative share card. Falls back to the default. */
  image?: string;
  imageAlt?: string;
  type?: 'website' | 'article' | 'profile';
  /** Keeps a page out of the index without keeping crawlers off it. */
  noindex?: boolean;
  /** Trail shown in the result, home excluded — it is added automatically. */
  breadcrumbs?: Array<{ name: string; path: string }>;
  /** Extra schema nodes merged into the page graph. */
  schema?: Record<string, unknown>[];
}

export const abs = (path: string) => new URL(path, SITE_URL).href;

/* ------------------------------------------------------------ the entity */

/**
 * TODO — supply and this becomes eligible for the Maps pack.
 * Set `postalAddress` to the real studio address and `hours` to the real
 * opening hours, then flip `LOCAL` to true. Leaving it false is deliberate:
 * a LocalBusiness node with no address is worse than none at all.
 */
const LOCAL = false;
const postalAddress = {
  streetAddress: '300 South Spring Street', // TODO
  addressLocality: '200 N Spring St', // TODO — e.g. 'Salt Lake City'
  addressRegion: 'CA',
  postalCode: '90012', // TODO
  addressCountry: 'US',
};
const hours = ['Mo-Fr 09:00-18:00']; // TODO — confirm

/**
 * The business, as one node.
 *
 * `ProfessionalService` is used rather than bare `Organization` because it is
 * a LocalBusiness subtype: it accepts areaServed, priceRange and hours, which
 * is what makes the node eligible for local treatment once the address lands.
 */
export function organization(): Record<string, unknown> {
  const node: Record<string, unknown> = {
    '@type': ['Organization', 'ProfessionalService'],
    '@id': ID.org,
    name: SITE_NAME,

    // Brand search is the highest-converting traffic a studio gets, and people
    // do not type the registered name. They type "JP media", "JP media group"
    // singular, or run the words together. Every spelling the business is
    // actually searched by is declared so Google resolves them all to one
    // entity instead of treating them as unrelated strings.
    alternateName: ['JP Media', 'JP Media Group', 'JPMedia', 'JP Media Groups Utah', 'JPMG', 'JP', 'jp'],

    url: SITE_URL,
    logo: { '@id': ID.logo },
    image: { '@id': ID.logo },
    description:
      'Creative agency specialising in audiovisual production, professional photography, music videos, branding and strategic marketing.',
    slogan: 'Every brand has a story worth telling',
    foundingDate: '2016',
    email: contact.email,
    telephone: contact.phone,

    // Where the work actually happens. Built from the same market records the
    // market pages render, so the schema and the visible pages can never drift
    // apart — and stated as states, not only as cities, because "California"
    // and "Los Angeles" are one fact to the studio and two searches to Google.
    areaServed: [
      ...markets.map((m) => ({
        '@type': m.kind,
        name: m.name,
        ...(m.region ? { address: { '@type': 'PostalAddress', addressRegion: m.region } } : {}),
      })),
      ...markets.flatMap((m) => m.cities.map((c) => ({ '@type': 'City', name: c }))),
      { '@type': 'Country', name: 'United States' },
    ],

    knowsAbout: [...KEYWORDS.core, ...KEYWORDS.services, ...KEYWORDS.places, ...marketKeywords],
    knowsLanguage: ['en', 'es'],

    // The five disciplines, as an offer catalogue. This is what lets Google
    // answer "what do they do" without parsing the prose.
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'Services',
      itemListElement: services.items.map((s, i) => ({
        '@type': 'Offer',
        position: i + 1,
        itemOffered: {
          '@type': 'Service',
          name: s.title,
          description: s.body,
          serviceType: s.title,
          provider: { '@id': ID.org },
        },
      })),
    },

    employee: team.members.map((m) => ({
      '@type': 'Person',
      name: m.name,
      jobTitle: m.role,
      email: m.email,
      worksFor: { '@id': ID.org },
    })),

    // Every profile the business controls. This is the single strongest signal
    // for entity resolution — add the Google Business Profile, YouTube, Vimeo,
    // LinkedIn, Behance and TikTok URLs here as they exist.
    sameAs: socials.map((s) => s.href),

    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'sales',
      email: contact.email,
      telephone: contact.phone,
      areaServed: ['US', 'CO'],
      availableLanguage: ['English', 'Spanish'],
    },
  };

  if (LOCAL) {
    node.address = { '@type': 'PostalAddress', ...postalAddress };
    node.openingHours = hours;
    node.priceRange = '$$';
  }

  return node;
}

/** The logo, as its own node so both the Organization and the site can cite it. */
export function logoNode(): Record<string, unknown> {
  return {
    '@type': 'ImageObject',
    '@id': ID.logo,
    url: abs('/icons/icon-512.png'),
    contentUrl: abs('/icons/icon-512.png'),
    width: 512,
    height: 512,
    caption: SITE_NAME,
  };
}

export function website(): Record<string, unknown> {
  return {
    '@type': 'WebSite',
    '@id': ID.website,
    url: SITE_URL,
    name: SITE_NAME,
    description:
      'Video production, professional photography and strategic marketing for brands, restaurants and artists.',
    publisher: { '@id': ID.org },
    inLanguage: LANG,
  };
}

/**
 * The breadcrumb trail. Home is prepended here so no page has to repeat it,
 * and the current page is included as the last item — Google drops trails that
 * do not terminate on the page they are served from.
 */
export function breadcrumbs(
  trail: Array<{ name: string; path: string }>,
  url: string,
): Record<string, unknown> | null {
  if (!trail.length) return null;
  const items = [{ name: 'Home', path: '/' }, ...trail];
  return {
    '@type': 'BreadcrumbList',
    '@id': `${url}#breadcrumb`,
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: abs(item.path),
    })),
  };
}

export function webPage(page: PageSeo, url: string): Record<string, unknown> {
  const node: Record<string, unknown> = {
    '@type': 'WebPage',
    '@id': `${url}#webpage`,
    url,
    name: page.title,
    description: page.description,
    isPartOf: { '@id': ID.website },
    about: { '@id': ID.org },
    primaryImageOfPage: { '@id': ID.logo },
    inLanguage: LANG,
  };
  if (page.breadcrumbs?.length) node.breadcrumb = { '@id': `${url}#breadcrumb` };
  return node;
}

/**
 * Assembles the page's whole graph as ONE script tag.
 *
 * A single `@graph` is deliberate. Multiple separate JSON-LD blocks are legal,
 * but nodes in different blocks cannot reference each other by @id, so the
 * Organization, the page and the breadcrumb end up as three unrelated islands.
 */
export function jsonLd(page: PageSeo, url: string): string {
  const graph = [
    organization(),
    logoNode(),
    website(),
    webPage(page, url),
    breadcrumbs(page.breadcrumbs ?? [], url),
    ...(page.schema ?? []),
  ].filter(Boolean);

  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph });
}

/* ------------------------------------------------------------ page copy */
/* Titles are front-loaded: the terms people search sit before the brand name,
   because Google truncates the tail and users scan the head. */

export const pages = {
  home: {
    // Two states in 61 characters, which is what fits. The home page carries
    // the brand and the two biggest markets; every other market is carried by
    // its own page, because one URL cannot be the best answer for five places.
    // "JP Media" rather than the full name is deliberate — it is a real
    // alternateName, it catches the brand searches people actually type, and
    // Google prints "JP Media Groups" above the title from the schema anyway.
    title: 'Photography, Video & Marketing — Utah & California | JP Media',
    description:
      'Creative agency for video production, photography and marketing in Utah, California, Florida, New York and Colombia. Music videos, commercials and food photography.',
    image: '/og/jp-media-groups.jpg',
    // A home page is the site root; a breadcrumb trail on it is noise.
    breadcrumbs: [],
  },

  contact: {
    title: 'Contact — Start a Project | JP Media Groups',
    description:
      'Tell JP Media Groups about your project. Video production, photography, music videos, branding and marketing in Utah, Miami, New York, Los Angeles and Colombia.',
    image: '/og/contact.jpg',
    imageAlt: 'Contact JP Media Groups — start a video, photography or marketing project.',
    breadcrumbs: [{ name: 'Contact', path: '/contact/' }],
    schema: [
      {
        '@type': 'ContactPage',
        '@id': `${SITE_URL}/contact/#contactpage`,
        url: `${SITE_URL}/contact/`,
        name: 'Contact JP Media Groups',
        mainEntity: { '@id': ID.org },
      },
    ],
  },

  /**
   * One record per market, built from the same data the page renders.
   *
   * These pages exist because a single home page cannot rank for Utah AND
   * California AND Florida at once — Google picks one subject per URL. A page
   * that names a market in its URL, its title, its H1 and its opening sentence
   * is the only thing that answers "marketing california", and no amount of
   * meta-tag work on the home page substitutes for it.
   *
   * They are deliberately NOT the same page with the place name swapped. Each
   * one leads with different disciplines and carries its own copy, because
   * near-identical location pages are doorway pages, and Google demotes those
   * rather than ranking them.
   */
  market(m: Market): PageSeo {
    return {
      // The market leads the title. Brand goes last: Google truncates the tail
      // and the searcher scans the head.
      title: `Marketing, Video & Photography in ${m.name} | JP Media`,
      description: m.metaDescription,
      breadcrumbs: [{ name: m.name, path: `/${m.slug}/` }],
      schema: [
        {
          '@type': 'Service',
          '@id': `${SITE_URL}/${m.slug}/#service`,
          name: `Marketing, video production and photography in ${m.name}`,
          description: m.lead,
          serviceType: m.leads,
          provider: { '@id': ID.org },
          areaServed: [
            {
              '@type': m.kind,
              name: m.name,
              ...(m.region
                ? { address: { '@type': 'PostalAddress', addressRegion: m.region } }
                : {}),
            },
            ...m.cities.map((c) => ({ '@type': 'City', name: c })),
          ],
          hasOfferCatalog: {
            '@type': 'OfferCatalog',
            name: `Services in ${m.name}`,
            itemListElement: m.leads.map((title, i) => {
              const s = services.items.find((x) => x.title === title);
              return {
                '@type': 'Offer',
                position: i + 1,
                itemOffered: {
                  '@type': 'Service',
                  name: `${title} — ${m.name}`,
                  description: s?.body ?? '',
                  provider: { '@id': ID.org },
                },
              };
            }),
          },
        },
      ],
    };
  },

  notFound: {
    title: 'Page Not Found | JP Media Groups',
    description:
      'That page does not exist. Head back to JP Media Groups — video production, photography and marketing in Utah, the United States and Colombia.',
    // A 404 that gets indexed competes with the pages that matter.
    noindex: true,
    breadcrumbs: [],
  },
} satisfies Record<string, PageSeo | ((m: Market) => PageSeo)>;
